name: Audit

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build using cargo cheef
        run: |
          cargo chef prepare --receipe-path recipe.json
          cargo chef cook --receipe-path recipe.json
          cargo build --release